// This code is normally generated by `go generate`. This example is
// provided to illustrate the structure of this package and to make
// `example.go` compile.
package entities

import "log/slog"

func init() {
	slog.Warn(
		"Using example 'entities' package. See 'README.md' for " +
			"instructions on generating 'entities' for your own setup.",
	)
}

type ZoneDomain struct {
	Home string
}

var Zone = ZoneDomain{
	Home: "zone.home",
}

type BinarySensorDomain struct {
	LivingRoomMotion string
	PantryDoor       string
}

var BinarySensor = BinarySensorDomain{
	LivingRoomMotion: "binary_sensor.living_room_motion",
	PantryDoor:       "binary_sensor.pantry_door",
}

type LightDomain struct {
	LivingRoomLamps string
	MainLights      string
	OutsideLights   string
	ChristmasLights string
}

var Light = LightDomain{
	LivingRoomLamps: "light.living_room_lamps",
	MainLights:      "light.main_lights",
	OutsideLights:   "light.outside_lights",
	ChristmasLights: "light.christmas_lights",
}
